### ISSUE TITLE
Options to turn-off all or some autolinking features

### ISSUE THREAD

**Issue by LukaszGrela** [micromark/micromark-extension-gfm#6] opened 2022-01-26 08:32 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

We would like to turn off all or some autolinking features, e.g. we love the url links but we dont need or desire the email autolinking.

### Solution

 It would be great if this would be possibile e.g. via options:
```
autolinking: "all"|"url"|"email"|"none"
```

### Alternatives

don't really know, maybe writing the links in a way the plugin doesnt recognise it?

**Comment by wooorm** [comment] 2022-01-26 08:39
1. This package follows GFM. Why would you use this but not want to follow GFM. 🤷‍♂️
2. What is so bad about emails be clickable?

**Comment by wooorm** [comment] 2022-01-26 08:42
And you can already turn off autolinking features. The syntax extensions are developed/released as separate packages.

**Comment by LukaszGrela** [comment] 2022-01-26 10:28
Ad. 2 Well, that's my requirement, no emails, but urls are fine, such weird business requirement. we're using `remark-gfm` which is using this `micromark` extension, and it is passing config, so it would be useful to have those options in such cases where one don't choose which plugins are used.
Ad. 1 GFM is not only about autolinking, I like GFM features but dont want some of the autolinking to work.

**Comment by wooorm** [comment] 2022-01-26 13:35
> Well, that's my requirement, [...] such weird business requirement

I recommend going to your boss and mentioning that it is better in the long run to follow (pseudo-)standards than another custom flavor of markdown.

Duplicate of remarkjs/remark-gfm#34

**Closed by wooorm** 2022-01-26 13:35 UTC
Labels: 🤞 phase/open
